[build]
  publish = "public"
  command = "hugo --gc --minify"
  functions = "functions"

[context.production.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.82.0"

[template.environment]
  REPO = "TimothyMamo/timothymamo.com"